#!/bin/sh

case $(printf "Select area\\nFull screen" | fuzzel --dmenu --minimal-lines -w 15) in
    "Select area")
        (grim -g "$(slurp)" - | tee /tmp/pic-selected-"$(date '+%y%m%d-%H%M-%S').png" | wl-copy --type image/png) &&
        notify-send -t 1000 "Screenshot saved to /tmp" ;;
    "Full screen")
        (grim - | tee /tmp/pic-full-"$(date '+%y%m%d-%H%M-%S').png" | wl-copy --type image/png) &&
        notify-send -t 1000 "Screenshot saved to /tmp" ;;
esac

