#!/bin/sh

INTERFACE=$(ip route | awk '/^default via/ {print $5; exit}')

if [ -z "$INTERFACE" ]; then
    exit
fi

read -r STATE < /sys/class/net/"$INTERFACE"/operstate

if [ "$STATE" = "up" ]; then
    case "$INTERFACE" in
        *en*) printf "  " ;;
        *wl*) printf "  " ;;
    esac
fi

