#!/bin/bash

OPTIONS="Cancel\n Shutdown\nﰇ Reboot\n Sleep\n Hibernate\n Lock"
SELECTED=$(echo -e "$OPTIONS" | dmenu -l 6)

case $SELECTED in
    " Shutdown") systemctl poweroff ;;
    "ﰇ Reboot") systemctl reboot ;;
    " Sleep") systemctl suspend ;;
    " Hibernate") systemctl hibernate ;;
    " Lock") slock ;;
    *) return ;;
esac

