#!/bin/sh

while getopts 'm:' FLAG; do
  case ${FLAG} in
    m) M_FLAG=${OPTARG} ;;
    *) ;;
  esac
done

OPTIONS="Cancel
 Shutdown
 Reboot
 Sleep
 Hibernate
 Lock"
SELECTED=$(printf '%s\n' "$OPTIONS" | dmenu -m "$M_FLAG" -l 6 -z 220)

case "$SELECTED" in
    " Shutdown") systemctl poweroff ;;
    " Reboot") systemctl reboot ;;
    " Sleep") systemctl suspend ;;
    " Hibernate") systemctl hibernate ;;
    " Lock") xset s activate ;;
    *) exit ;;
esac
