#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

. "$HOME"/.config/X11/xprofile

dwmblocks &

while true; do
    # Log stderror to a file 
    # dwm 2> ~/.dwm.log
    # No error logging
    dwm >/dev/null 2>&1
done

