#!/bin/sh

BAT=$(< /sys/class/power_supply/BAT0/capacity)

[ $(< /sys/class/power_supply/AC/online) == 1 ] && ICON="" ||
	if  [ "$BAT" -gt 0 ] && [ "$BAT" -lt 13 ]
	then
		ICON=" "
	elif [ "$BAT" -gt 12 ] && [ "$BAT" -lt 38 ]
	then
		ICON=" "
	elif [ "$BAT" -gt 37 ] && [ "$BAT" -lt 63 ]
	then
		ICON=" "
	elif [ "$BAT" -gt 62 ] && [ "$BAT" -lt 88 ]
	then
        ICON=" "
	else
		ICON=" "
	fi

printf "\x0c$ICON \x0b$BAT%%"

