#!/bin/bash

read -r WIFI < /sys/class/net/wlp0s20f3/operstate
read -r UTP < /sys/class/net/enp4s0/operstate

if [ "$UTP" = "up" ]
then
    printf "\x0c \x0b"
elif [ "$WIFI" = "up" ]
then
    printf "\x0c " 
fi

