#!/bin/bash

INTERFACE=$(ip route | awk '/^default via/ {print $5; exit}')

read -r STATE < /sys/class/net/"$INTERFACE"/operstate

if [ "$STATE" = "up" ]
then
    case "$INTERFACE" in
        *en*) printf "\x0c \x0b" ;;
        *wl*) printf "\x0c \x0b"  ;;
    esac
fi

