#!/bin/bash

OPTIONS="Cancel\n Shutdown\nﰇ Reboot\n Sleep\n Hibernate\n Lock"
X=$(xdpyinfo | grep dimensions | awk '{ print $2 }' | cut -d x -f 1)
X=$((X-230))
Y=40
SELECTED=$(echo -e "$OPTIONS" | dmenu -l 6 -x "$X" -y "$Y" -z 200)

case $SELECTED in
    " Shutdown") systemctl poweroff ;;
    "ﰇ Reboot") systemctl reboot ;;
    " Sleep") systemctl suspend ;;
    " Hibernate") systemctl hibernate ;;
    " Lock") slock ;;
    *) return ;;
esac

