#!/bin/sh

if bluetoothctl show | grep -q "Powered: yes"; then
    printf "  "
fi

case $BLOCK_BUTTON in
    1)
        eval "$(xdotool getmouselocation --shell)"
        Z=250
        X=$((X-Z))
        Y=29
        dmenu-bluetooth -x $X -y $Y -z $Z >/dev/null
        ;;
    2)
        info="$(bluetoothctl info 2>/dev/null)"
        
        name="$(
          printf '%s\n' "$info" |
          awk -F': ' '
            /^[[:space:]]*Connected:/ { if ($2=="yes") c=1 }
            /^[[:space:]]*Name:/      { n=$2 }
            END { if (c && n!="") print n }
          '
        )"
        
        if [ -n "$name" ]; then
            dunstify -r 5555 "Connected to: $name"
        else
            dunstify -r 5555 "No bluetooth device connected"
        fi

        pkill -RTMIN+6 dwmblocks
        ;;
esac

