#!/bin/sh

if lsusb | grep -q "Bluetooth"; then
    if bluetoothctl show | grep -q "Powered: yes"; then
        printf " "
    fi
fi

case $BLOCK_BUTTON in
    1)
        eval "$(xdotool getmouselocation --shell)"
        Z=250
        X=$((X-Z))
        Y=29
        dmenu-bluetooth -x $X -y $Y -z $Z >/dev/null ;;
    2)
        if [ "$(bluetoothctl paired-devices)" = "" ]; then
            dunstify -r 5555 "No bluetooth device connected"
        else
            dunstify -r 5555 "$(bluetoothctl paired-devices | awk '{$1=""; $2=""; sub("  ", "")}1')"
        fi
esac

