#!/bin/sh

COLOR=^c#F38BA8^

INTERFACE=$(ip route | awk '/^default via/ {print $5; exit}')

if [ -z "$INTERFACE" ]; then
    exit
fi

read -r STATE < /sys/class/net/"$INTERFACE"/operstate

if [ "$STATE" = "up" ]; then
    case "$INTERFACE" in
        *en*) printf " %s" "$COLOR";;
        *wl*) printf " %s" "$COLOR";;
    esac
fi

case $BLOCK_BUTTON in
    1)
        eval "$(xdotool getmouselocation --shell)"
        Z=400
        X=$((X-Z))
        Y=29
        networkmanager_dmenu -l 20 -x $X -y $Y -z $Z >/dev/null 2>&1 ;;
    2)
        dunstify -r 5555 -u 0 "$(nmcli -t -f name connection show --active)" ;;
esac

