#!/bin/sh

INTERFACE=$(ip route | awk '/^default via/ {print $5; exit}')

if [ -z "$INTERFACE" ]; then
    exit
fi

read -r STATE < /sys/class/net/"$INTERFACE"/operstate

if [ "$STATE" = "up" ]; then
    case "$INTERFACE" in
        *en*) printf "  " ;;
        *wl*) printf "  " ;;
    esac
fi

case $BLOCK_BUTTON in
    1)
        Y=29
        Z=400
        read -r MONITOR X <<EOF
$(get-monitor-x)
EOF
        X=$((X - Z))
        [ "$X" -lt 0 ] && X=0
        networkmanager_dmenu -m "$MONITOR" -x "$X" -y "$Y" -z "$Z" -l 20 >/dev/null 2>&1
        ;;
    2)
        dunstify -r 5555 -u 0 "Connected to: $(nmcli -t -f name connection show --active | head -n 1)"
        pkill -RTMIN+5 dwmblocks
        ;;
esac

