#!/bin/sh

printf "   "

[ "$BLOCK_BUTTON" != "1" ] && exit 0

eval "$(xdotool getmouselocation --shell)"
Z=200
X=$((X-Z))
Y=29

OPTIONS="Cancel\n Shutdown\n Reboot\n Suspend\n Hibernate\n Lock"

CHOICE=$(printf "%b" "$OPTIONS" | dmenu -l 6 -x "$X" -y "$Y" -z "$Z")

case "$CHOICE" in
    " Shutdown")   systemctl poweroff ;;
    " Reboot")     systemctl reboot ;;
    " Suspend")    systemctl suspend ;;
    " Hibernate")  systemctl hibernate ;;
    " Lock")       loginctl lock-session ;;
esac

