#!/bin/sh

printf "   "

[ "$BLOCK_BUTTON" != "1" ] && exit 0

Y=29
Z=200
OPTIONS="Cancel\n Shutdown\n Reboot\n Suspend\n Hibernate\n Lock"
read -r MONITOR X <<EOF
$(get-monitor-x)
EOF
X=$((X - Z))
[ "$X" -lt 0 ] && X=0

CHOICE=$(printf "%b" "$OPTIONS" | dmenu -m "$MONITOR" -x "$X" -y "$Y" -z "$Z" -l 6)

case "$CHOICE" in
    " Shutdown")   systemctl poweroff ;;
    " Reboot")     systemctl reboot ;;
    " Suspend")    systemctl suspend ;;
    " Hibernate")  systemctl hibernate ;;
    " Lock")       loginctl lock-session ;;
esac

