#!/bin/sh

CITY=
TEMP="$(curl -s "wttr.in/$CITY?0Tq")"

[ -z "$TEMP" ] && exit

IFS=
printf ' %s' "$(echo "$TEMP" | grep -m 1 -Eo -e '-?[[:digit:]].*°.+')"

case "$BLOCK_BUTTON" in
    1)
        WEATHER=$(echo "$TEMP" | while read -r LINE ; do
            LINE=$(echo "$LINE" | sed 's/ *$//g')
            printf "%s\n" "$LINE"
        done
        )

        MAX_LENGTH=$(echo "$WEATHER" | awk ' { if ( length > x ) { x = length; y = $0 } }END{ print y }' | wc -m)

        WEATHER=$(echo "$WEATHER" | while read -r LINE ; do
            LINE_LENGTH=$(echo "$LINE" | wc -m)
            i=0
            while [ $i -le $(( MAX_LENGTH - LINE_LENGTH - 1 )) ]; do
                LINE="${LINE} "
                i=$(( i + 1 ))
            done
            printf "%s\n" "$LINE"
        done
        )

        dunstify -r 5555 -u 0 "$WEATHER"
esac

