#!/bin/bash

VOLUME=$(pamixer --get-volume)

if pamixer --get-volume-human | grep -q "muted"; then
    printf "\x0bﱝ "
    exit
elif [ "$VOLUME" = 0 ]; then
    ICON="\x0b婢 "
elif [ "$VOLUME" -lt 33 ]; then
	ICON="\x0c奄 \x0b"
elif [ "$VOLUME" -lt 66 ]; then
	ICON="\x0c奔 \x0b"
else
	ICON="\x0c墳 \x0b"
fi

[ "$VOLUME" -gt 100 ] && pactl set-sink-volume 0 100%

printf "$ICON$VOLUME%%"

