#!/bin/bash

VOLUME=$(pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $((SINK + 1)) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

if pactl list sinks | grep -q "Mute: yes"; then
    printf "\x0bﱝ "
    exit
elif [ "$VOLUME" = 0 ]; then
    ICON="\x0b婢 "
elif [ "$VOLUME" -lt 33 ]; then
	ICON="\x0c奄 \x0b"
elif [ "$VOLUME" -lt 66 ]; then
	ICON="\x0c奔 \x0b"
else
	ICON="\x0c墳 \x0b"
fi

[ "$VOLUME" -gt 100 ] && pactl set-sink-volume 0 100%

printf "$ICON$VOLUME%%"

