#!/bin/sh

OFFSET_RE="\+([-0-9]+)\+([-0-9]+)"

set -- $(xwininfo -id "$(xdotool getwindowfocus)" | grep "Absolute upper-left" |
    awk '{print $NF}')

# cache for xrandr because it's slow
if [ ! -f /tmp/xr ]; then
    xrandr > /tmp/xr
fi
xr="$(cat /tmp/xr)"

monitor="$(\
echo "$xr" | grep -w connected | sed -r "s/^([^ ]*).*\b([-0-9]+)x([-0-9]+)$OFFSET_RE.*$/\1 \2 \3 \4 \5/" |
sort -nk4,5 |
while read -r name width height xoff yoff; do
    if [ "$1" -ge "$xoff" ] \
        && [ "$2" -ge "$yoff" ] \
        && [ "$1" -lt "$((xoff+width))" ] \
        && [ "$2" -lt "$((yoff+height))" ]
    then
        echo "$name"
        break
    fi
done)"

# If we found a monitor, echo it out, otherwise print an error.
if [ -n "$monitor" ]; then
  echo "$xr" | grep -w connected  | sed 's/primary //' | grep "$monitor" | awk -F'[ +]' '{print $3}'
  exit 0
else
  echo "Couldn't find any monitor for the current window." >&2
  exit 1
fi

