#!/bin/sh
#
# Write/remove a task to do later.
#
# Select an existing entry to remove it from the file, or type a new entry to
# add it.
#

while getopts 'm:' FLAG; do
  case ${FLAG} in
    m) M_FLAG=${OPTARG} ;;
    *) ;;
  esac
done

FILE=$HOME/.todo
touch "$FILE"
HEIGHT=$(wc -l "$FILE" | awk '{print $1}')

CMD=$(dmenu -m "$M_FLAG" -l "$HEIGHT" "$@" < "$FILE")
while [ -n "$CMD" ]; do
 	if grep -q "^$CMD\$" "$FILE"; then
		grep -v "^$CMD\$" "$FILE" > "$FILE.$$"
		mv "$FILE.$$" "$FILE"
        HEIGHT=$(( HEIGHT - 1 ))
 	else
		echo "$CMD" >> "$FILE"
		HEIGHT=$(( HEIGHT + 1 ))
 	fi

	CMD=$(dmenu -m "$M_FLAG" -l "$HEIGHT" "$@" < "$FILE")
done

exit 0

