#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

export XSECURELOCK_BACKGROUND_COLOR="#171727"
export XSECURELOCK_AUTH_BACKGROUND_COLOR="#7287FD"
export XSECURELOCK_AUTH_FOREGROUND_COLOR="#0E0E1E"
export XSECURELOCK_PASSWORD_PROMPT="asterisks"
export XSECURELOCK_SHOW_KEYBOARD_LAYOUT=0
export XSECURELOCK_WAIT_TIME_MS=20000

xrdb -merge "$HOME/.config/X11/Xresources" &
setxkbmap -layout hu -option caps:escape &
xbindkeys -f "$HOME/.config/X11/xbindkeysrc" &
xset r rate 250 30 s 300 20 &

xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &
xidlehook --detect-sleep --not-when-fullscreen --not-when-audio \
    --timer 600 "systemctl suspend-then-hibernate" '' &
feh --no-fehbg --bg-fill "$HOME/Pictures/Wallpapers/21.jpg" &

autostart="dwmblocks picom dunst udiskie"

read -r CHASSIS_TYPE < /sys/class/dmi/id/chassis_type
if [ "$CHASSIS_TYPE" = 9 ] || [ "$CHASSIS_TYPE" = 10 ]; then
    autostart="$autostart batsignal libinput-gestures"
fi

for program in $autostart; do
  "$program" &
done

#exec dwm
while true; do
    # Log stderror to log file
    dwm 2> ~/.dwm.log
#    # No error logging
#    dwm >/dev/null 2>&1
done

