#!/bin/sh

BATFILE=/sys/class/power_supply/BAT0/capacity
ACFILE=/sys/class/power_supply/AC/online

[ -r "$BATFILE" ] || exit 0
read -r BAT < "$BATFILE"

AC=0
[ -r "$ACFILE" ] && read -r AC < "$ACFILE"

if [ "$AC" -eq 1 ]; then
    ICON=""
else
    if   [ "$BAT" -lt 20 ]; then ICON=""
    elif [ "$BAT" -lt 40 ]; then ICON=""
    elif [ "$BAT" -lt 60 ]; then ICON=""
    elif [ "$BAT" -lt 80 ]; then ICON=""
    else                         ICON=""
    fi
fi

printf " %s %s" "$ICON" "$BAT%"
#printf " %s " "$ICON"

case ${BLOCK_BUTTON:-} in
    2)
        dunstify -r 5555 -u 0 -t 1000 "Battery at $BAT%"
        pkill -RTMIN+4 dwmblocks
        ;;
esac

