#!/bin/sh

VOLUME=$(pamixer --get-volume-human)
[ -z "$VOLUME" ] && exit

case $BLOCK_BUTTON in
    1) $TERMINAL --class wiremix -e wiremix & ;;
    2) dunstify -r 5555 -u 0 -t 1000 "Volume: $VOLUME" ;;
    3) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
esac

if [ "$VOLUME" = "muted" ]; then
    printf "  "
    exit
fi

VOLUME=${VOLUME%\%}

if [ "$VOLUME" -gt 100 ]; then
    pactl set-sink-volume @DEFAULT_SINK@ 100%
    VOLUME=100
fi

if [ "$VOLUME" -eq 0 ]; then
    ICON=""
elif [ "$VOLUME" -lt 50 ]; then
	ICON=""
else
	ICON=""
fi

printf " %s " "$ICON"

